### ISSUE TITLE
Android building error: `cannot find symbol import io.flutter.plugin.common.PluginRegistry.Registrar`

### ISSUE THREAD

**Issue by Azzeccagarbugli** [flutter-webrtc/callkeep#201]
Hello there,

When I'm trying to build the app with the current version of the package, now I'm getting the following error _(exclusive on Android)_:

```
/Users/.../.pub-cache/git/callkeep-85641625db759787c8e94f4e990553b9fd2c5f10/android/src/main/java/com/github/cloudwebrtc/flutter_callkeep/FlutterCallkeepPlugin.java:15: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
/Users/.../.pub-cache/git/callkeep-85641625db759787c8e94f4e990553b9fd2c5f10/android/src/main/java/com/github/cloudwebrtc/flutter_callkeep/FlutterCallkeepPlugin.java:30: error: cannot find symbol
  public static void registerWith(Registrar registrar) {
                                  ^
  symbol:   class Registrar
  location: class FlutterCallkeepPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':callkeep:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 11s
Error: Gradle task assembleDebug failed with exit code 1
```

This seems to be happening on the newest **Flutter 3.29.0** and this could be an [issue](https://github.com/ekasetiawans/flutter_background_service/issues/496) similar to this.

[Migrating and supporting the new Android plugins API](https://docs.flutter.dev/release/breaking-changes/plugin-api-migration) would be the best solution, I guess, so thanks a lot for considering this ✨

**Comment by md-riaz** [comment]
facing the same issue, how to solve?

**Comment by Sahad-uniconnect** [comment]
This issue has been fixed and merged!  You can now use the latest update with the following dependency configuration:

**pubspec.yaml**
```
callkeep:
  git:
    url: https://github.com/flutter-webrtc/callkeep.git
    ref: b55d64476a2888b3981a57d4400390269a137b34
```

**Comment by Sahad-uniconnect** [comment]
This fix is merged in [PR #202](https://github.com/flutter-webrtc/callkeep/pull/202).
Maintainers @cloudwebrtc , please review and close the issue if no further action is needed.

**Comment by md-riaz** [comment]
thanks but #109 issue persists when setup callkeep in fcm background message
